theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Lauryn's Open Source Journey
description: Join me as I blog about my experience as a self-taught programmer and open source contributor!
author: Lauryn Menard
